In [1]:
import sys
import numpy as np
sys.path.append("/mnt/d/Python/minifympi/")
from minifympi.wrappers import parallel

ImportError: cannot import name 'MinifyMPI' from 'minifympi.core' (/mnt/d/Python/minifympi/minifympi/core/__init__.py)

In [ ]:
n_procs = 4
n_tasks = 10
@parallel(n_procs, n_tasks)
@decorator2
def test(a:'S', b:'s', c=None, *args, **kwargs)->'G,g,g':
    a *= 2
    # a = np.sin(a)
    print(c)
    return a, b, c

a = np.arange(n_tasks*2).reshape(n_tasks, -1)
b = list(range(n_procs))
c = np.arange(n_procs*2).reshape(n_procs, -1)
returns = test(a, b, c, 5, 10, 11, d=3)
print('returns', returns)

In [ ]:
print('returns', returns)

In [ ]:
code = '''
a = 2
b = 3
c = 1/0
'''
exec(code)

In [ ]:
exec(code)

In [ ]:
import traceback

def test():
    print(1/0)

code = '''
a = 2
b = 3
# test()
c = 1/0
'''
code = compile(code, '<string>', 'exec')


try:
    exec(code)
except Exception as e:
    print(code)
    traceback.print_exc()


In [ ]:
exec(code)

In [ ]:
%%writefile tmp.py
def test():
    print(1/0)
    
a = 2
b = 3
# test()
c = e/0


In [11]:
import traceback
from colorama import Fore, Back, Style
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import Terminal256Formatter

import re




try:
    filename = "tmp.py"
    with open(filename, "r") as file:
        source_code = file.read()
    code = compile(source_code, filename, 'exec')
    exec(code)
except Exception as e:
    style = 'perldoc'
    exception_str = traceback.format_exc()
    line_number = re.findall('File "tmp.py", line (\d+),', exception_str)
    line_number = int(line_number[-1])

    highlighted_code = highlight(
        source_code, 
        PythonLexer(), 
        Terminal256Formatter(style=style)
    )

    for number, line in enumerate(highlighted_code.split('\n')):
        number += 1
        arrow = f'{Fore.GREEN}---->' if number == line_number else '     '
        lineno = f'{arrow}{Fore.BLUE}{number:4d}{Fore.RESET}'
        print(f'{lineno} {line}')
        # number += 1
    print()
    print(f'{Fore.RED}{"-"*75}{Fore.RESET}')

    highlighted_code = highlight(
        exception_str, 
        PythonLexer(), 
        Terminal256Formatter(style=style)
    )
    print(highlighted_code)


        1 def test():
        2     print(1/0)
        3     
        4 a = 2
        5 b = 3
        6 # test()
---->   7 c = e/0
        8 

---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ipykernel_31472/2155288172.py", line 17, in <module>
    exec(code)
  File "tmp.py", line 7, in <module>
    c = e/0
        ^
NameError: name 'e' is not defined



In [7]:
from rich.syntax import Syntax
from rich.console import Console
from rich.theme import Theme


try:
    filename = "tmp.py"
    with open(filename, "r") as file:
        source_code = file.read()
    code = compile(source_code, filename, 'exec')
    exec(code)
except Exception as e:
    #LINK - for more style, please read https://pygments.org/styles/
    theme = 'lightbulb'
    width = 80
    console = Console()
    syntax = Syntax(source_code, "python", theme=theme, line_numbers=True)
    console.print(syntax, width=width)
    console.print_exception(theme=theme, width=width)
    # s = console.format_exception(e)
    # print(e)


  1 def test():                                                                 
  2     print(1/0)                                                              
  3                                                                             
  4 a = 2                                                                       
  5 b = 3                                                                       
  6 # test()                                                                    
  7 c = e/0                                                                     
  8                                                                             

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ in <module>:11                                                               │
│                                                                              │
│    8 │   with open(filename, "r") as file:                                   │
│    9 │   │   source_code = file.read()                                       │
│   10 │   code = compile(source_code, filename, 'exec')                       │
│ ❱ 11 │   exec(code)                                                          │
│   12 except Exception as e:                                                  │
│   13 │   #LINK - for more style, please read https://pygments.org/styles/    │
│   14 │   theme = 'lightbulb'                                                 │
│                                                                              │
│ /mnt/d/Python/minifympi/tests/tmp.py:7 in <module>                           │
│                                                                              │
│   4 a = 2                                                                    │
│   5 b = 3                                                                    │
│   6 # test()                                                                 │
│ ❱ 7 c = e/0                                                                  │
│   8                                                                          │
╰──────────────────────────────────────────────────────────────────────────────╯
NameError: name 'e' is not defined

In [6]:
console

<console width=115 ColorSystem.TRUECOLOR>

In [1]:
import os

In [3]:
os.path.dirname('/mnt/d/test.py')

'/mnt/d'

In [ ]:
exec(code)

In [8]:
import traceback
from rich import traceback as rich_traceback
from rich import print

# 替换标准库中的 traceback 模块
# rich_traceback.install()

try:
    # 引发一个异常
    c = 1 / 0
except ZeroDivisionError:
    # 打印 traceback 信息
    traceback_str = traceback.format_exc()
    print(traceback_str)


Traceback (most recent call last):
  File "/tmp/ipykernel_471/948580055.py", line 10, in <module>
    c = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero

In [ ]:
lambda: (njit, )

In [ ]:
from rich.syntax import Syntax

my_code = '''
def iter_first_last(values: Iterable[T]) -&gt; Iterable[Tuple[bool, bool, T]]:
    """Iterate and generate a tuple with a flag for first and last value."""
    iter_values = iter(values)
    try:
        previous_value = next(iter_values)
    except StopIteration:
        return
    first = True
    for value in iter_values:
        yield first, False, previous_value
        first = False
        previous_value = value
    yield first, True, previous_value
'''
syntax = Syntax(my_code, "python", theme="monokai", line_numbers=True)
print(syntax)

In [ ]:
import rich

In [ ]:
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import Terminal256Formatter


In [ ]:
highlighted_code = highlight(
    s, 
    PythonLexer(), 
    Terminal256Formatter(style='default')
)
print(highlighted_code)

In [10]:
import uuid

random_uuid = uuid.uuid4()
print(random_uuid)


3c605801-0819-430d-8d5a-d22760830c05

In [15]:
import numpy as np
data = np.random.rand(1000, 10)

def my_sum(data):
    res = data.sum(axis=1)
    return res

my_sum(data)

array([4.96027849, 5.48652903, 3.80186374, 3.81207392, 6.59427699,
       4.06265082, 7.11909986, 4.62412544, 3.99538114, 4.41469671,
       4.22822812, 3.11288333, 3.32241351, 6.08440185, 5.52047221,
       5.47755664, 5.88006201, 5.28528501, 4.66798547, 6.38380524,
       5.42455143, 4.72496703, 5.0404149 , 5.65845393, 5.82098681,
       5.00565456, 3.81487249, 4.46778832, 4.26035397, 4.93131405,
       5.33692626, 5.16858997, 6.24281253, 4.71700354, 5.38320577,
       4.33436189, 3.94501588, 5.44250035, 4.20392998, 5.68635321,
       4.82383236, 3.37136063, 6.71561966, 6.50078307, 2.62774438,
       4.87646067, 5.68924699, 5.29910452, 5.54982859, 5.80352831,
       5.58553664, 4.89735333, 5.67778343, 5.15202041, 4.06403616,
       5.13943746, 4.15345968, 5.03577563, 3.49211059, 3.96863207,
       3.86082941, 6.36542116, 5.74209631, 4.99906399, 6.49571108,
       3.76396492, 4.43451843, 5.26738876, 6.89918428, 5.12955194,
       3.80896837, 5.13624136, 4.55003325, 5.36367658, 3.71090

In [18]:
N = np.array(0, dtype='i')

In [21]:
h = 1/N
s = 0

/tmp/ipykernel_471/3389590107.py:1: RuntimeWarning: divide by zero encountered in divide
  h = 1/N


In [ ]:
spawn-parallel

In [6]:
8*1024*1024*64*8/1024**3

4.0

In [5]:
512/8

64.0

# find_decorator_requires

In [18]:
import sys
import numpy as np
from numba import jit
import inspect
sys.path.append("/mnt/d/Python/minifympi/")

In [10]:
from minifympi.core import mmp

In [28]:
def test2(a):
    print(a)

# @mmp.find_requires
@jit
def test(a, b):
    test2(a+b)


mmp.find_requires(test, {'jit': jit})

{}

In [29]:
mmp.find_decorator_requires(test)

AttributeError: 'CPUDispatcher' object has no attribute '__globals__'

In [20]:
print(inspect.getsource(test))

@jit
def test(a, b):
    test2(a+b)



In [6]:
def test():
    data = (1, 2)
    return data

In [7]:
test()

(1, 2)

In [8]:
import types

In [18]:
data = np.arange(100).reshape(10, -1)

In [19]:
np.array_split(data, 3, axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]),
 array([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [20]:
class Loc:
    def test(self, a):
        print(a)

class M:
    def __init__(self) -> None:
        self.loc = Loc()

In [21]:
m = M()

In [25]:
getattr(m, 'loc').test(1)

1


In [33]:
getattr(data, 'dtypwe', 'None')

AttributeError: 'numpy.ndarray' object has no attribute 'dtypwe'

In [34]:
type(data).__name__

'ndarray'

In [44]:
metadata = [{'type': 'ndarray', 'shape': (2,), 'dtype': 'int64'}, {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}, {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}, {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}]
meta = {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}

In [52]:
print('\n'.join([f'sub{i}: {meta}' for i, meta in enumerate(metadata)]))

sub0: {'type': 'ndarray', 'shape': (2,), 'dtype': 'int64'}
sub1: {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}
sub2: {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}
sub3: {'type': 'ndarray', 'shape': (3,), 'dtype': 'int64'}


False

In [53]:
1290+3150-600

3840

In [58]:
ave, res = divmod(10, 6)

# 分派任务

In [34]:
axis = 1
n_procs = 4
data = np.random.randint(0, 1000, (10, 15, 4))

task_count = np.ones(n_procs, int)*data.shape[axis]//n_procs
task_count[:data.shape[axis]%n_procs] += 1

count = task_count*np.prod(data.shape)/data.shape[axis]
count = task_count*np.prod(data.shape)/data.shape[axis]
displ = np.zeros_like(count)
displ[1:] = np.cumsum(count)[:-1]
task_count, count, displ

(array([4, 4, 4, 3]),
 array([160., 160., 160., 120.]),
 array([  0., 160., 320., 480.]))

In [59]:
from mpi4py import MPI
from mpi4py.util.dtlib import from_numpy_dtype

In [63]:
from_numpy_dtype(np.float32)

(2,)

In [101]:
data = np.arange(36).reshape(6, 6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [102]:
data[:, :2]

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

In [110]:
data_split = np.array_split(data, 4, axis=1)
for item in data_split:
    print(item.shape)

(6, 2)
(6, 2)
(6, 1)
(6, 1)


In [118]:
np.concatenate(data_split, axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [180]:
class MBase:
    @staticmethod
    def decorator(func):
        def wrapper(self, *args, **kwargs):
            res = self.m.decorator(func)(self, *args, **kwargs)
            return res
        return wrapper

class M1(MBase):
    pass
        

class M2(MBase):
    main = False
    def decorator(self, func):
        if self.main:
            return super().decorator(func)
        else:
            def wrapper(*args, **kwargs):
                pass
                # res = func(*args, **kwargs)
            return wrapper

In [172]:
m0 = MBase()
@m0.decorator
def test():
    print(1)
test()


TypeError: MBase.decorator.<locals>.wrapper() missing 1 required positional argument: 'self'

In [163]:
m1 = M1()
@m1.decorator
def test():
    print(1)

test()

<function test at 0x7f16001ba480>
1


In [164]:
m2 = M2()

@m2.decorator
def test():
    print(1)

test()

In [186]:
class Bcast:
    def __init__(self, m) -> None:
        self.m = m
    
    @MBase.decorator
    def test(self):
        print(1)
        return 1

    def test2(self):
        print(2)
        return 2

In [189]:
b = Bcast(m1)
b.test()

<function Bcast.test at 0x7f16001b9440>
1


1

In [170]:
b.test2

method

In [12]:
class M1:
    def __init__(self) -> None:
        self.Bcast = Bcast(self)
    pass

class M2:
    def __init__(self) -> None:
        self.Bcast = Bcast(self)
            
        def main(resp):
            self.Bcast._main(resp)
        
        self.Bcast.main = main
        


class Bcast:
    def __init__(self, m) -> None:
        self.m = m
        self.name = 'test'

    def run(self, resp, data=None):
        if self.is_main:
            self._main(resp, data)
        if self.is_root:
            self._root(resp, data)
        if self.is_sub:
            self._sub(resp, data)


    def _main(self, resp):
        print('_main', resp)
        pass

    def _root(self, resp):
        print('_root', resp)
        pass

    def _sub(self, resp):
        print('_sub', resp)
        pass

In [13]:
m = M1()
m.Bcast.main(1)

AttributeError: 'Bcast' object has no attribute 'main'

In [15]:
m1 = m 
m2 = m

In [16]:
m1 is m2

True

In [213]:
m = M2()
m.Bcast.main(3)

_main 3


In [17]:
import re

In [25]:
re.findall('^\s*@(\w+)', ' @abc.')

['abc']

In [35]:
code = '''
@parallel(n_procs)
def test(a, b):
    return a + b, a
'''
dec_code = 'parallel(n_procs)'
re.sub(f'(\s*)(@{dec_code})', r'\1#\2', code)

'\n@parallel(n_procs)\ndef test(a, b):\n    return a + b, a\n'

In [46]:
re.findall(f'@parallel(n_procs)', code)

[]

In [48]:
code.replace(dec_code, '#@'+dec_code)

'\n#@@parallel(n_procs)\ndef test(a, b):\n    return a + b, a\n'

In [40]:
print(dec_code)
print(code)

@parallel(n_procs)

@parallel(n_procs)
def test(a, b):
    return a + b, a



In [218]:
data.__subp__

<method-wrapper '__sub__' of numpy.ndarray object at 0x7f16003d8f30>

In [219]:
def test(a, *args, c=None, **kwargs):
    print(a, args, c, kwargs)

In [222]:
test(1, 2, 3, d=5, c=4)

1 (2, 3) 4 {'d': 5}


In [1]:
a = {1: 2}
a.update({1: 4})

In [2]:
a

{1: 4}

In [6]:
import sys
import numpy as np
sys.path.append("/mnt/d/Python/minifympi/")

from minifympi.old_core import MinifyMPI

In [49]:
a = {1: 2}

In [54]:
a.get(1, '') or 'ab'

2

In [58]:
from functools import reduce
import numpy as np

In [74]:
data = [(3,2), (3,2), (2,2), (2,2)]

In [75]:
reduce(lambda x, y: (x[0]+y[0], *x[1:]), data)

(10, 2)

In [81]:
data = np.array([1, 2, 3, 5])
np.cumprod(data)

array([ 1,  2,  6, 30])

In [82]:
data.prod()

30

In [84]:
np.cumsum([1, 2, 3])

array([1, 3, 6])

In [1]:
import sys
import numpy as np
sys.path.append("/mnt/d/Python/minifympi/")
# from minifympi.old_core import MinifyMPI
from minifympi.core.notebook import MinifyMPI
from pandas.io.parsers.readers import read_csv as rc

In [2]:
mmp = MinifyMPI(4, 10)
mmp.start_comm()

In [3]:
mmp.scatter['a'] = [1, 2, 3, 4]
code = 'mmp.gs["a"] = 6'
mmp.exec(code)

@mmp.parallel
def test(a, b):
    return a + b

mmp['res0'] = mmp.test(mmp['a'], 4)

print(mmp.gather['res0'])

(main)[proc0] [parallel] 
#@mmp.parallel
def test(a, b):
    return a + b

(main)[proc0] [parallel] ['mmp']
[10, 10, 10, 10]


In [4]:
mmp.close_comm()

In [49]:
mmp.gs

{'mmp': <minifympi.core.notebook.MinifyMPI at 0x7f1c84105fd0>, 'a': None}

In [3]:
mmp.find_requires(test)

{'rc': <function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_

# find requirement

In [84]:
from numba import jit
from textwrap import indent, dedent
import ast, astor
import types
import re
import inspect
from pandas.io.parsers.readers import read_csv as rc


In [52]:
def find_requires(func, g=None, ignores=None):
    ''' 
    Find dependency libraries and functions for `func`.

    Parameters
    ----------
    func : function
        Any function.
    '''
    ignores = ignores if ignores else ["__builtins__", "__file__"]
    g = g if g else getattr(func, '__globals__', globals())
    requires = find_require_code(func, g, ignores)
    return {require: g[require] for require in requires if require in g}


def find_require_code(func, g, ignores=None):
    requires = [
        name for name in func.__code__.co_names
        if name not in ignores \
        and name != func.__code__.co_name \
        and hasattr(sys.modules['__main__'], name)
    ]
    for item in requires:
        if item in g and isinstance(g[item], types.FunctionType):
            for key in find_requires(g[item], ignores + requires):
                if key not in requires:
                    requires.append(key)
    return requires


def find_require_decorator(func):
    # NOTE - 不支持class类型的装饰器
    # class类型的装饰器需要初始化，我们不知道如何初始化，因此不支持class类型的
    # 装饰器
    # TODO
    # 如果有class类型的装饰器，我们应当弹出提示，表示不支持。
    code = dedent(inspect.getsource(func))
    decorators = [line.strip() for line in code.split('\n') if line.startswith('@')]
    decorators = [re.findall('@(.+'+('?)\(' if '(' in line else ')'), line)[0] for line in decorators]
    requires_decorators = find_requires(
        eval('lambda: ({})'.format(','.join(decorators))), 
        getattr(func, '__globals__', globals())
    )
    return requires_decorators




In [50]:
@jit
def test():
    # read_csv
    rc
    test2()

def test2():
    print(1)
    
print(inspect.getsource(test))

@jit
def test():
    # read_csv
    rc
    test2()



In [53]:
find_requires(test)
find_require_decorator(test)

{'rc': <function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_

In [45]:
find_require_decorator(test)

{'jit': <function numba.core.decorators.jit(signature_or_function=None, locals={}, cache=False, pipeline_class=None, boundscheck=None, **options)>}

In [40]:
tree = ast.parse(inspect.getsource(test))
tree.body

In [55]:
a = lambda x: None

In [56]:
a.__code__.co_name

'<lambda>'

In [58]:
test.__code__.co_names

('rc', 'test2')

In [68]:
isinstance(test2, type(a))

True

In [76]:
import ast

# 示例代码，可以替换为你需要分析的代码
code = """
@jit
def test():
    rc
    test3()

def test2(func):
    @test5
    def test4():
        print(2)
    print(1)
    return func

@test2
def test3():
    print(3)

"""

decorators = []

# 解析代码为抽象语法树
tree = ast.parse(code)

# 遍历抽象语法树，提取函数定义并获取装饰器
for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef):
        function_name = node.name
        decorators = [ast.dump(dec).strip() for dec in node.decorator_list]
        print(f"Function '{function_name}' has decorators: {decorators}")

Function 'test' has decorators: ["Name(id='jit', ctx=Load())"]
Function 'test2' has decorators: []
Function 'test3' has decorators: ["Name(id='test2', ctx=Load())"]
Function 'test4' has decorators: ["Name(id='test5', ctx=Load())"]


In [72]:
function_name, decorators

('my_function',
 ["Name(id='decorator1', ctx=Load())", "Name(id='decorator2', ctx=Load())"])

In [73]:
node.decorator_list

AttributeError: 'Load' object has no attribute 'decorator_list'

In [98]:
code = """
@jit
def test():
    rc
    test3()
"""

code = dedent(inspect.getsource(rc))


# 解析代码为抽象语法树
tree = ast.parse(code)
# decorators = []

# 遍历抽象语法树，提取函数定义并获取装饰器
for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef):
        function_name = node.name
        decorators = [ast.dump(dec).strip() for dec in node.decorator_list]
        print(f"Function '{function_name}' has decorators: {decorators}")

Function 'read_csv' has decorators: ['Call(func=Name(id=\'Appender\', ctx=Load()), args=[Call(func=Attribute(value=Name(id=\'_doc_read_csv_and_table\', ctx=Load()), attr=\'format\', ctx=Load()), args=[], keywords=[keyword(arg=\'func_name\', value=Constant(value=\'read_csv\')), keyword(arg=\'summary\', value=Constant(value=\'Read a comma-separated values (csv) file into DataFrame.\')), keyword(arg=\'see_also_func_name\', value=Constant(value=\'read_table\')), keyword(arg=\'see_also_func_summary\', value=Constant(value=\'Read general delimited file into DataFrame.\')), keyword(arg=\'_default_sep\', value=Constant(value="\',\'")), keyword(arg=\'storage_options\', value=Subscript(value=Name(id=\'_shared_docs\', ctx=Load()), slice=Constant(value=\'storage_options\'), ctx=Load())), keyword(arg=\'decompression_options\', value=BinOp(left=Subscript(value=Name(id=\'_shared_docs\', ctx=Load()), slice=Constant(value=\'decompression_options\'), ctx=Load()), op=Mod(), right=Constant(value=\'filepat

In [111]:
node = ast.parse(code).body[0]
decs = [ast.dump(dec).strip() for dec in node.decorator_list] if isinstance(node, ast.FunctionDef) else []

In [103]:
print(decs[0])

Call(func=Name(id='Appender', ctx=Load()), args=[Call(func=Attribute(value=Name(id='_doc_read_csv_and_table', ctx=Load()), attr='format', ctx=Load()), args=[], keywords=[keyword(arg='func_name', value=Constant(value='read_csv')), keyword(arg='summary', value=Constant(value='Read a comma-separated values (csv) file into DataFrame.')), keyword(arg='see_also_func_name', value=Constant(value='read_table')), keyword(arg='see_also_func_summary', value=Constant(value='Read general delimited file into DataFrame.')), keyword(arg='_default_sep', value=Constant(value="','")), keyword(arg='storage_options', value=Subscript(value=Name(id='_shared_docs', ctx=Load()), slice=Constant(value='storage_options'), ctx=Load())), keyword(arg='decompression_options', value=BinOp(left=Subscript(value=Name(id='_shared_docs', ctx=Load()), slice=Constant(value='decompression_options'), ctx=Load()), op=Mod(), right=Constant(value='filepath_or_buffer')))])], keywords=[])


In [113]:
ast.dump(node.decorator_list[0])

'Call(func=Name(id=\'Appender\', ctx=Load()), args=[Call(func=Attribute(value=Name(id=\'_doc_read_csv_and_table\', ctx=Load()), attr=\'format\', ctx=Load()), args=[], keywords=[keyword(arg=\'func_name\', value=Constant(value=\'read_csv\')), keyword(arg=\'summary\', value=Constant(value=\'Read a comma-separated values (csv) file into DataFrame.\')), keyword(arg=\'see_also_func_name\', value=Constant(value=\'read_table\')), keyword(arg=\'see_also_func_summary\', value=Constant(value=\'Read general delimited file into DataFrame.\')), keyword(arg=\'_default_sep\', value=Constant(value="\',\'")), keyword(arg=\'storage_options\', value=Subscript(value=Name(id=\'_shared_docs\', ctx=Load()), slice=Constant(value=\'storage_options\'), ctx=Load())), keyword(arg=\'decompression_options\', value=BinOp(left=Subscript(value=Name(id=\'_shared_docs\', ctx=Load()), slice=Constant(value=\'decompression_options\'), ctx=Load()), op=Mod(), right=Constant(value=\'filepath_or_buffer\')))])], keywords=[])'

In [115]:
c = node.decorator_list[0]

In [118]:
hasattr

'Appender'

In [121]:
rc.__module__

'pandas.io.parsers.readers'

In [125]:
from minifympi.core.__init__ import a

In [128]:
rc.__name__

'read_csv'

In [129]:
test.__name__

'test'

In [75]:
decorators

["Name(id='test2', ctx=Load())"]

In [1]:
import sys
import numpy as np
sys.path.append("/mnt/d/Python/minifympi/")
from minifympi.old_core import MinifyMPI
from pandas.io.parsers.readers import read_csv as rc
from functools import wraps, update_wrapper, reduce
import ast, astor
from textwrap import indent, dedent
import inspect
from minifympi.utils.code import *
from numba import jit

In [2]:
def test2(func):
    return func

@jit
# @test2
def test():
    return 1 + 2

In [3]:
print(get_source_with_requires(test, gs=globals(), requires={'np': np}))

decs ['jit']
decs []
import numpy as np
from numba.core.decorators import jit


@jit
# @test2
def test():
    return 1 + 2



In [62]:
from typing import Any


class MPIVar:
    '''
    TODO - MPIVar 的展示
    我们最好再Mpi类内维护一个metadata的字典，用于记录进程内变量的信息，
    通过MPIVar来标记变量时，就会展示相关的信息，例如类型，大小和传输类型
    等信息。
    '''
    def __init__(self, mmp, key) -> None:
        self.mmp = mmp
        self.key = key
    

    def __str__(self) -> str:
        return f"<<MPIVar> name='{self.key}'>"
    
    def __repr__(self) -> str:
        return self.__str__()


class MMP:
    gs = {'a': 1, 'b':2}
    def __getitem__(self, keys):
        '''
        获取进程中的变量。这是一种标记符号，并不会放回进程里的数据。
        仅在并行函数内作为参数使用，以及删除进程内数据时使用。
        '''
        _keys = keys
        if isinstance(keys, str):
            keys = (keys,)
        elif not isinstance(keys, (list, tuple)):
            raise KeyError(keys)
        for key in keys:
            if key not in self.gs:
                raise KeyError(f'key `{key}` not Found.')

        vars = tuple(MPIVar(self, key) for key in keys)            
        if isinstance(_keys, str):
            return vars[0]
        else:
            return vars
        

    def __setitem__(self, keys, values):
        if isinstance(values, MPIFunction):
            print(keys, values)
            print(values.bound)
            values.send_arguments()
        else:
            '''bcast'''


    def parallel(self, func, gs=None, ignores=None, requires=None):
        # if not self.is_main:
        #     return func
        code = get_source_with_requires(func, gs, ignores, requires)
        print(code)
        mpi_func = MPIFunction(self, func)
        setattr(self, func.__code__.co_name, mpi_func)
        update_wrapper(mpi_func, func)
        return func
    

class MPIFunction:
    def __init__(self, mmp, func):
        self.mmp = mmp
        self.func = func
        self.bound = {}
    
    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        sig = inspect.signature(self.func)
        bound = sig.bind(*args, **kwargs)
        self.bound['pargs'] = bound.arguments
        self.bound['args'] = {f'arg{i}': item for i, item in enumerate(bound.arguments.pop('args', {}))}
        self.bound['kwargs'] = bound.arguments.pop('kwargs', {})
        return self

    def send_arguments(self):
        resp = {}
        for arg_type, dct in self.bound.items():
            for key, value in dct.items():
                if isinstance(value, MPIVar):
                    print(key, value)
                if isinstance(value, np.ndarray):
                    self.mmp.Bcast(storage='ls', **{key: value})
                else:
                    self.mmp.bcast(storage='ls', **{key: value})



In [63]:
mmp = MMP()
@mmp.parallel
def test(a, b, *args, **kwargs):
    print(a, b)

mmp['a'] = mmp.test(*mmp['a', 'b'], 3, c=4)

decs ['mmp.parallel']
@mmp.parallel
def test(a, b, *args, **kwargs):
    print(a, b)

a <__main__.MPIFunction object at 0x7f30b3ee8810>
{'pargs': {'a': <<MPIVar> name='a'>, 'b': <<MPIVar> name='b'>}, 'args': {'arg0': 3}, 'kwargs': {'c': 4}}
a <<MPIVar> name='a'>
b <<MPIVar> name='b'>


In [80]:
arguments = {
    'pargs': ['mmp.gs["a"]', 'mmp.ls["b"]'], 
    'args': ['mmp.ls["0"]'], 
    'kwargs': ['key=mmp.ls["d"]']
}

In [81]:
arguments_code = ''
if 'pargs' in arguments:
    arguments_code += ', '.join(arguments['pargs']) + ', '
if 'args' in arguments:
    arguments_code += ', '.join(arguments['args']) + ', '
if 'kwargs' in arguments:
    arguments_code += ', '.join(arguments['kwargs']) + ', '

arguments_code

'mmp.gs["a"], mmp.ls["b"], mmp.ls["0"], key=mmp.ls["d"], '

In [86]:
from itertools import chain

In [96]:
', '.join((chain(*arguments.values())))

'mmp.gs["a"], mmp.ls["b"], mmp.ls["0"], key=mmp.ls["d"]'

In [21]:
from numba import jit, types
@jit
def test(a, b, *args, **kwargs):
    return a, b

In [20]:
test(1, 2, 3, 4)

(1, 2)

In [1]:
dct_annotations = {
    's': 'scatter',
    'S': 'Scatter',
    'b': 'bcast',
    'B': 'Bcast',
    'g': 'gather',
    'G': 'Gather',
}

In [5]:
dct_annotations

{'s': 'scatter',
 'S': 'Scatter',
 'b': 'bcast',
 'B': 'Bcast',
 'g': 'gather',
 'G': 'Gather',
 'scatter': 'scatter',
 'Scatter': 'Scatter',
 'bcast': 'bcast',
 'Bcast': 'Bcast',
 'gather': 'gather',
 'Gather': 'Gather'}

In [11]:
140*1024/60/60/1.6

24.88888888888889